import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/style/globals.css";
import NavbarMenu from "@/components/Navbar";
import FooterPart from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    name: "hadi"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<AuthProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarMenu />
        <main>
          {children}

        </main>
        <FooterPart />
      </body>
    </html>
  </AuthProvider>
  );
}
